//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for citeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="citeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="followup"/>
 *     &lt;enumeration value="supersedes"/>
 *     &lt;enumeration value="retraction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "citeValues")
@XmlEnum
public enum CiteValues {

    @XmlEnumValue("followup")
    FOLLOWUP("followup"),
    @XmlEnumValue("supersedes")
    SUPERSEDES("supersedes"),
    @XmlEnumValue("retraction")
    RETRACTION("retraction");
    private final String value;

    CiteValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CiteValues fromValue(String v) {
        for (CiteValues c: CiteValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
