//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="idValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TT-ICRS-TOPO"/>
 *     &lt;enumeration value="UTC-ICRS-TOPO"/>
 *     &lt;enumeration value="TT-FK5-TOPO"/>
 *     &lt;enumeration value="UTC-FK5-TOPO"/>
 *     &lt;enumeration value="GPS-ICRS-TOPO"/>
 *     &lt;enumeration value="GPS-ICRS-TOPO"/>
 *     &lt;enumeration value="GPS-FK5-TOPO"/>
 *     &lt;enumeration value="GPS-FK5-TOPO"/>
 *     &lt;enumeration value="TT-ICRS-GEO"/>
 *     &lt;enumeration value="UTC-ICRS-GEO"/>
 *     &lt;enumeration value="TT-FK5-GEO"/>
 *     &lt;enumeration value="UTC-FK5-GEO"/>
 *     &lt;enumeration value="GPS-ICRS-GEO"/>
 *     &lt;enumeration value="GPS-ICRS-GEO"/>
 *     &lt;enumeration value="TDB-ICRS-BARY"/>
 *     &lt;enumeration value="TDB-FK5-BARY"/>
 *     &lt;enumeration value="UTC-GEOD-TOPO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "idValues")
@XmlEnum
public enum IdValues {

    @XmlEnumValue("TT-ICRS-TOPO")
    TT_ICRS_TOPO("TT-ICRS-TOPO"),
    @XmlEnumValue("UTC-ICRS-TOPO")
    UTC_ICRS_TOPO("UTC-ICRS-TOPO"),
    @XmlEnumValue("TT-FK5-TOPO")
    TT_FK_5_TOPO("TT-FK5-TOPO"),
    @XmlEnumValue("UTC-FK5-TOPO")
    UTC_FK_5_TOPO("UTC-FK5-TOPO"),
    @XmlEnumValue("GPS-ICRS-TOPO")
    GPS_ICRS_TOPO("GPS-ICRS-TOPO"),
    @XmlEnumValue("GPS-FK5-TOPO")
    GPS_FK_5_TOPO("GPS-FK5-TOPO"),
    @XmlEnumValue("TT-ICRS-GEO")
    TT_ICRS_GEO("TT-ICRS-GEO"),
    @XmlEnumValue("UTC-ICRS-GEO")
    UTC_ICRS_GEO("UTC-ICRS-GEO"),
    @XmlEnumValue("TT-FK5-GEO")
    TT_FK_5_GEO("TT-FK5-GEO"),
    @XmlEnumValue("UTC-FK5-GEO")
    UTC_FK_5_GEO("UTC-FK5-GEO"),
    @XmlEnumValue("GPS-ICRS-GEO")
    GPS_ICRS_GEO("GPS-ICRS-GEO"),
    @XmlEnumValue("TDB-ICRS-BARY")
    TDB_ICRS_BARY("TDB-ICRS-BARY"),
    @XmlEnumValue("TDB-FK5-BARY")
    TDB_FK_5_BARY("TDB-FK5-BARY"),
    @XmlEnumValue("UTC-GEOD-TOPO")
    UTC_GEOD_TOPO("UTC-GEOD-TOPO");
    private final String value;

    IdValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdValues fromValue(String v) {
        for (IdValues c: IdValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
