//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.xml.voevent.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WhyName_QNAME = new QName("", "Name");
    private final static QName _WhyInference_QNAME = new QName("", "Inference");
    private final static QName _WhyDescription_QNAME = new QName("", "Description");
    private final static QName _WhyReference_QNAME = new QName("", "Reference");
    private final static QName _WhyConcept_QNAME = new QName("", "Concept");
    private final static QName _ParamValue_QNAME = new QName("", "Value");
    private final static QName _WhoAuthorLogoURL_QNAME = new QName("", "logoURL");
    private final static QName _WhoAuthorTitle_QNAME = new QName("", "title");
    private final static QName _WhoAuthorContactPhone_QNAME = new QName("", "contactPhone");
    private final static QName _WhoAuthorContactEmail_QNAME = new QName("", "contactEmail");
    private final static QName _WhoAuthorContactName_QNAME = new QName("", "contactName");
    private final static QName _WhoAuthorContributor_QNAME = new QName("", "contributor");
    private final static QName _WhoAuthorShortName_QNAME = new QName("", "shortName");
    private final static QName _TimeInstantISOTime_QNAME = new QName("", "ISOTime");
    private final static QName _TimeInstantTimeOffset_QNAME = new QName("", "TimeOffset");
    private final static QName _TimeInstantTimeScale_QNAME = new QName("", "TimeScale");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.xml.voevent.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObservatoryLocation }
     * 
     */
    public ObservatoryLocation createObservatoryLocation() {
        return new ObservatoryLocation();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ObsDataLocation }
     * 
     */
    public ObsDataLocation createObsDataLocation() {
        return new ObsDataLocation();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link ObservationLocation }
     * 
     */
    public ObservationLocation createObservationLocation() {
        return new ObservationLocation();
    }

    /**
     * Create an instance of {@link Value3 }
     * 
     */
    public Value3 createValue3() {
        return new Value3();
    }

    /**
     * Create an instance of {@link EventIVORN }
     * 
     */
    public EventIVORN createEventIVORN() {
        return new EventIVORN();
    }

    /**
     * Create an instance of {@link WhereWhen }
     * 
     */
    public WhereWhen createWhereWhen() {
        return new WhereWhen();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link How }
     * 
     */
    public How createHow() {
        return new How();
    }

    /**
     * Create an instance of {@link AstroCoordSystem }
     * 
     */
    public AstroCoordSystem createAstroCoordSystem() {
        return new AstroCoordSystem();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link What }
     * 
     */
    public What createWhat() {
        return new What();
    }

    /**
     * Create an instance of {@link TR }
     * 
     */
    public TR createTR() {
        return new TR();
    }

    /**
     * Create an instance of {@link TimeInstant }
     * 
     */
    public TimeInstant createTimeInstant() {
        return new TimeInstant();
    }

    /**
     * Create an instance of {@link Why }
     * 
     */
    public Why createWhy() {
        return new Why();
    }

    /**
     * Create an instance of {@link Position3D }
     * 
     */
    public Position3D createPosition3D() {
        return new Position3D();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link Value2 }
     * 
     */
    public Value2 createValue2() {
        return new Value2();
    }

    /**
     * Create an instance of {@link AstroCoords }
     * 
     */
    public AstroCoords createAstroCoords() {
        return new AstroCoords();
    }

    /**
     * Create an instance of {@link Who }
     * 
     */
    public Who createWho() {
        return new Who();
    }

    /**
     * Create an instance of {@link Who.Author }
     * 
     */
    public Who.Author createWhoAuthor() {
        return new Who.Author();
    }

    /**
     * Create an instance of {@link Citations }
     * 
     */
    public Citations createCitations() {
        return new Citations();
    }

    /**
     * Create an instance of {@link Inference }
     * 
     */
    public Inference createInference() {
        return new Inference();
    }

    /**
     * Create an instance of {@link Position2D }
     * 
     */
    public Position2D createPosition2D() {
        return new Position2D();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link VOEvent }
     * 
     */
    public VOEvent createVOEvent() {
        return new VOEvent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name", scope = Why.class)
    public JAXBElement<String> createWhyName(String value) {
        return new JAXBElement<String>(_WhyName_QNAME, String.class, Why.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Inference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Inference", scope = Why.class)
    public JAXBElement<Inference> createWhyInference(Inference value) {
        return new JAXBElement<Inference>(_WhyInference_QNAME, Inference.class, Why.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description", scope = Why.class)
    public JAXBElement<String> createWhyDescription(String value) {
        return new JAXBElement<String>(_WhyDescription_QNAME, String.class, Why.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference", scope = Why.class)
    public JAXBElement<Reference> createWhyReference(Reference value) {
        return new JAXBElement<Reference>(_WhyReference_QNAME, Reference.class, Why.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Concept", scope = Why.class)
    public JAXBElement<String> createWhyConcept(String value) {
        return new JAXBElement<String>(_WhyConcept_QNAME, String.class, Why.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value", scope = Param.class)
    public JAXBElement<String> createParamValue(String value) {
        return new JAXBElement<String>(_ParamValue_QNAME, String.class, Param.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description", scope = Param.class)
    public JAXBElement<String> createParamDescription(String value) {
        return new JAXBElement<String>(_WhyDescription_QNAME, String.class, Param.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference", scope = Param.class)
    public JAXBElement<Reference> createParamReference(Reference value) {
        return new JAXBElement<Reference>(_WhyReference_QNAME, Reference.class, Param.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name", scope = Inference.class)
    public JAXBElement<String> createInferenceName(String value) {
        return new JAXBElement<String>(_WhyName_QNAME, String.class, Inference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description", scope = Inference.class)
    public JAXBElement<String> createInferenceDescription(String value) {
        return new JAXBElement<String>(_WhyDescription_QNAME, String.class, Inference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference", scope = Inference.class)
    public JAXBElement<Reference> createInferenceReference(Reference value) {
        return new JAXBElement<Reference>(_WhyReference_QNAME, Reference.class, Inference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Concept", scope = Inference.class)
    public JAXBElement<String> createInferenceConcept(String value) {
        return new JAXBElement<String>(_WhyConcept_QNAME, String.class, Inference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logoURL", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorLogoURL(String value) {
        return new JAXBElement<String>(_WhoAuthorLogoURL_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorTitle(String value) {
        return new JAXBElement<String>(_WhoAuthorTitle_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactPhone", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorContactPhone(String value) {
        return new JAXBElement<String>(_WhoAuthorContactPhone_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactEmail", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorContactEmail(String value) {
        return new JAXBElement<String>(_WhoAuthorContactEmail_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactName", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorContactName(String value) {
        return new JAXBElement<String>(_WhoAuthorContactName_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contributor", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorContributor(String value) {
        return new JAXBElement<String>(_WhoAuthorContributor_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shortName", scope = Who.Author.class)
    public JAXBElement<String> createWhoAuthorShortName(String value) {
        return new JAXBElement<String>(_WhoAuthorShortName_QNAME, String.class, Who.Author.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISOTime", scope = TimeInstant.class)
    public JAXBElement<String> createTimeInstantISOTime(String value) {
        return new JAXBElement<String>(_TimeInstantISOTime_QNAME, String.class, TimeInstant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeOffset", scope = TimeInstant.class)
    public JAXBElement<Float> createTimeInstantTimeOffset(Float value) {
        return new JAXBElement<Float>(_TimeInstantTimeOffset_QNAME, Float.class, TimeInstant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeScale", scope = TimeInstant.class)
    public JAXBElement<String> createTimeInstantTimeScale(String value) {
        return new JAXBElement<String>(_TimeInstantTimeScale_QNAME, String.class, TimeInstant.class, value);
    }

}
