//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Part of WhereWhen
 * 
 * <p>Java class for ObsDataLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObsDataLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ObservatoryLocation" type="{http://www.ivoa.net/xml/VOEvent/v2.0}ObservatoryLocation"/>
 *         &lt;element name="ObservationLocation" type="{http://www.ivoa.net/xml/VOEvent/v2.0}ObservationLocation"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsDataLocation", propOrder = {

})
public class ObsDataLocation {

    @XmlElement(name = "ObservatoryLocation", required = true)
    protected ObservatoryLocation observatoryLocation;
    @XmlElement(name = "ObservationLocation", required = true)
    protected ObservationLocation observationLocation;

    /**
     * Gets the value of the observatoryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ObservatoryLocation }
     *     
     */
    public ObservatoryLocation getObservatoryLocation() {
        return observatoryLocation;
    }

    /**
     * Sets the value of the observatoryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservatoryLocation }
     *     
     */
    public void setObservatoryLocation(ObservatoryLocation value) {
        this.observatoryLocation = value;
    }

    /**
     * Gets the value of the observationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationLocation }
     *     
     */
    public ObservationLocation getObservationLocation() {
        return observationLocation;
    }

    /**
     * Sets the value of the observationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationLocation }
     *     
     */
    public void setObservationLocation(ObservationLocation value) {
        this.observationLocation = value;
    }

}
