//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ионГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/VOEvent/v2.0")
package net.ivoa.xml.voevent.v2;
