//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Who" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Who" minOccurs="0"/>
 *         &lt;element name="What" type="{http://www.ivoa.net/xml/VOEvent/v2.0}What" minOccurs="0"/>
 *         &lt;element name="WhereWhen" type="{http://www.ivoa.net/xml/VOEvent/v2.0}WhereWhen" minOccurs="0"/>
 *         &lt;element name="How" type="{http://www.ivoa.net/xml/VOEvent/v2.0}How" minOccurs="0"/>
 *         &lt;element name="Why" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Why" minOccurs="0"/>
 *         &lt;element name="Citations" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Citations" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reference" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Reference" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}token" fixed="2.0" />
 *       &lt;attribute name="ivorn" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="role" type="{http://www.ivoa.net/xml/VOEvent/v2.0}roleValues" default="observation" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "VOEvent")
public class VOEvent {

    @XmlElement(name = "Who")
    protected Who who;
    @XmlElement(name = "What")
    protected What what;
    @XmlElement(name = "WhereWhen")
    protected WhereWhen whereWhen;
    @XmlElement(name = "How")
    protected How how;
    @XmlElement(name = "Why")
    protected Why why;
    @XmlElement(name = "Citations")
    protected Citations citations;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Reference")
    protected Reference reference;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String version;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String ivorn;
    @XmlAttribute
    protected RoleValues role;

    /**
     * Gets the value of the who property.
     * 
     * @return
     *     possible object is
     *     {@link Who }
     *     
     */
    public Who getWho() {
        return who;
    }

    /**
     * Sets the value of the who property.
     * 
     * @param value
     *     allowed object is
     *     {@link Who }
     *     
     */
    public void setWho(Who value) {
        this.who = value;
    }

    /**
     * Gets the value of the what property.
     * 
     * @return
     *     possible object is
     *     {@link What }
     *     
     */
    public What getWhat() {
        return what;
    }

    /**
     * Sets the value of the what property.
     * 
     * @param value
     *     allowed object is
     *     {@link What }
     *     
     */
    public void setWhat(What value) {
        this.what = value;
    }

    /**
     * Gets the value of the whereWhen property.
     * 
     * @return
     *     possible object is
     *     {@link WhereWhen }
     *     
     */
    public WhereWhen getWhereWhen() {
        return whereWhen;
    }

    /**
     * Sets the value of the whereWhen property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhereWhen }
     *     
     */
    public void setWhereWhen(WhereWhen value) {
        this.whereWhen = value;
    }

    /**
     * Gets the value of the how property.
     * 
     * @return
     *     possible object is
     *     {@link How }
     *     
     */
    public How getHow() {
        return how;
    }

    /**
     * Sets the value of the how property.
     * 
     * @param value
     *     allowed object is
     *     {@link How }
     *     
     */
    public void setHow(How value) {
        this.how = value;
    }

    /**
     * Gets the value of the why property.
     * 
     * @return
     *     possible object is
     *     {@link Why }
     *     
     */
    public Why getWhy() {
        return why;
    }

    /**
     * Sets the value of the why property.
     * 
     * @param value
     *     allowed object is
     *     {@link Why }
     *     
     */
    public void setWhy(Why value) {
        this.why = value;
    }

    /**
     * Gets the value of the citations property.
     * 
     * @return
     *     possible object is
     *     {@link Citations }
     *     
     */
    public Citations getCitations() {
        return citations;
    }

    /**
     * Sets the value of the citations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citations }
     *     
     */
    public void setCitations(Citations value) {
        this.citations = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "2.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the ivorn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvorn() {
        return ivorn;
    }

    /**
     * Sets the value of the ivorn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvorn(String value) {
        this.ivorn = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link RoleValues }
     *     
     */
    public RoleValues getRole() {
        if (role == null) {
            return RoleValues.OBSERVATION;
        } else {
            return role;
        }
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleValues }
     *     
     */
    public void setRole(RoleValues value) {
        this.role = value;
    }

}
