//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 12:19:09 ÉÏÎç CST 
//


package net.ivoa.xml.voevent.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 *  What: Event Characterization. This is the part of the data model that is
 *         chosen by the Authoer of the event rather than the IVOA. There can be Params, that may be in
 *         Groups, and Tables, and simpleTimeSeries. There can also be Description and Reference as
 *         with most VOEvent elements. 
 * 
 * <p>Java class for What complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="What">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Param" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Group" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Table" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Table" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Reference" type="{http://www.ivoa.net/xml/VOEvent/v2.0}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "What", propOrder = {
    "paramOrGroupOrTable"
})
public class What {

    @XmlElements({
        @XmlElement(name = "Reference", type = Reference.class),
        @XmlElement(name = "Group", type = Group.class),
        @XmlElement(name = "Description", type = String.class),
        @XmlElement(name = "Param", type = Param.class),
        @XmlElement(name = "Table", type = Table.class)
    })
    protected List<Object> paramOrGroupOrTable;

    /**
     * Gets the value of the paramOrGroupOrTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramOrGroupOrTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamOrGroupOrTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * {@link Group }
     * {@link String }
     * {@link Param }
     * {@link Table }
     * 
     * 
     */
    public List<Object> getParamOrGroupOrTable() {
        if (paramOrGroupOrTable == null) {
            paramOrGroupOrTable = new ArrayList<Object>();
        }
        return this.paramOrGroupOrTable;
    }

}
